services:
  - name: facebook_server
    type: web
    env: node
    region: oregon # Cambia esto por tu regi√≥n preferida (ej. frankfurt para Europa)
    buildCommand: npm install
    startCommand: npm run serve
    plan: free
    branch: main
    autoDeploy: true
